<b>DOCUMENTATION</b> (Notes)<br>
13.1, 4.1 files in lying->irrelevant, lying->probe are missing.

In [257]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from statistics import mean
import csv
from sklearn.preprocessing import MinMaxScaler
# import modin.pandas as pd        # Modin import as a parallel computing library

# Tenserflow import
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping

In [258]:
import csv
import os
from pathlib import Path,PureWindowsPath
from fnmatch import fnmatch
import winsound
import os,glob

In [259]:
import winsound
duration = 1000  # milliseconds
freq = 440  # Hz

In [347]:
import os,glob
def path_list():
    paths=[]
    folder_path = r"C:\Users\mrsub\ML\Minor-Project I\All data for 14 electrodes and 30 subjects\All Data csv\Lying\Target\Target Excel\Validation"
    for filename in glob.glob(os.path.join(folder_path, '*.xlsx')):
        with open(filename, 'r') as f:
    #     text = f.read()
        paths.append(filename)
    #     print (len(text))
    return paths

In [348]:
paths=path_list()
#print(paths[:10])

In [349]:
len(paths)

18

In [350]:
def loading():
    sixth=[]
    count=0
    for i in range(len(paths)):
        filename = paths[i]
        data =pd.read_excel(filename,header=None)
        data.dropna(inplace = True)
#         print((data.loc[9:10,:15199]).shape)
        count+=1
        print(count)
        sixth.append(data.loc[20])
    winsound.Beep(freq, duration)
    winsound.Beep(freq, duration)
    winsound.Beep(freq, duration)
    return sixth

In [351]:
sixth=loading()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [352]:
print(sixth)

[0        25.3191
1        25.1513
2        24.9834
3        24.4799
4        24.1442
          ...   
16379    -1.1906
16380    -0.8549
16381    -0.3514
16382     0.3200
16383     0.6557
Name: 20, Length: 16384, dtype: float64, 0       -6.1891
1       -5.5177
2       -5.0141
3       -4.5106
4       -3.8392
          ...  
16379    3.1868
16380    3.0190
16381    3.0190
16382    3.3547
16383    3.3547
Name: 20, Length: 16384, dtype: float64, 0        1.4916
1        2.1630
2        2.3308
3        2.3308
4        2.1630
          ...  
16379   -6.4196
16380   -6.4196
16381   -6.4196
16382   -6.7553
16383   -6.9231
Name: 20, Length: 16384, dtype: float64, 0         6.5404
1         6.7083
2         7.0440
3         7.0440
4         7.0440
          ...   
16379   -44.3899
16380   -40.6972
16381   -36.1654
16382   -31.6335
16383   -26.9338
Name: 20, Length: 16384, dtype: float64, 0       -28.4321
1       -27.5929
2       -27.0893
3       -26.5858
4       -25.9144
          ...   
16379  

In [353]:
print(np.shape(sixth))

(18, 16384)


In [354]:
# hi=np.asarray(sixth) 
# hii=hi.reshape(38,15200)
# req_data=hii

In [355]:
req_data=np.asarray(sixth)            # converting to np array

In [356]:
#norm=np.zeros(req_data.shape)
# maxi=np.max(req_data[0])
# mini=np.min(req_data[0])

Sci-Kit learn scaler

In [357]:
# #req=req_data[0:2]
# scaler = MinMaxScaler()
# scaler.fit(req_data)
# data=scaler.transform(req_data)

In [358]:
print(np.shape(req_data))

(18, 16384)


In [359]:
def min_max():
    norm=np.zeros(req_data.shape)
    for i in range(req_data.shape[0]):
        maxi=np.max(req_data[i])
        mini=np.min(req_data[i])
        for j in range(req_data.shape[1]):
            norm[i:i+1,j:j+1]=(req_data[i:i+1,j:j+1]-mini)/(maxi-mini)
    winsound.Beep(freq, duration)
    return norm

In [360]:
norm = min_max()

In [361]:
print(norm)

[[0.73880824 0.73794724 0.73708573 ... 0.60708968 0.61053471 0.61225723]
 [0.38473283 0.38879435 0.39184079 ... 0.44043562 0.44246638 0.44246638]
 [0.67376242 0.68004198 0.6816114  ... 0.59976954 0.59662977 0.59506035]
 ...
 [0.76972418 0.77375993 0.77577901 ... 0.60273123 0.58658462 0.57043681]
 [0.27278928 0.27035078 0.26791228 ... 0.18592368 0.20177356 0.21640382]
 [0.57426205 0.58618076 0.60107826 ... 0.26311076 0.26311076 0.26311076]]


For time being norm ie. customized scaling shall be used instead of scikit learn preprocessor

In [362]:
count=0
for i in range(norm.shape[0]):
    count+=1
    print(norm[i].max())
    print(count)

1.0
1
1.0
2
1.0
3
1.0
4
1.0
5
1.0
6
1.0
7
1.0
8
1.0
9
1.0
10
1.0
11
1.0
12
1.0
13
1.0
14
1.0
15
1.0
16
1.0
17
1.0
18


In [363]:
norm_df=pd.DataFrame(norm)
norm_df.to_excel(r"C:\Users\mrsub\ML\Minor-Project I\All data for 14 electrodes and 30 subjects\Normalised Excel\Eleventh\target_val_norm_l.xlsx",index=False)

In [364]:
norm_df.shape

(18, 16384)

<b>Main Code</b>

intially numpy array is irr,probe,target (row wise) we hen make three columns of it

In [388]:
def open_file():
#     paths=[] 
    var=Path("C:/Users/mrsub/ML/Minor-Project I/All data for 14 electrodes and 30 subjects/Normalised Excel/Eleventh/Validation")
    folder_path = str(input("Enter file Name with extension "))
    folder_path=var/folder_path
    path=PureWindowsPath(folder_path)     #Unix to windows path
    print(path)

    data =pd.read_excel(path,header=None)
    data.dropna(inplace = True)

    winsound.Beep(freq, duration)
    winsound.Beep(freq, duration)
    winsound.Beep(freq, duration)
    return data

In [389]:
data=open_file()
print(data)

Enter file Name with extension target_val_norm_h.xlsx
C:\Users\mrsub\ML\Minor-Project I\All data for 14 electrodes and 30 subjects\Normalised Excel\Eleventh\Validation\target_val_norm_h.xlsx
       0         1         2         3         4         5         6      \
0   0.000000  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000   
1   0.468319  0.458022  0.450013  0.444292  0.438571  0.437427  0.442003   
2   0.633494  0.637814  0.632055  0.617655  0.596057  0.574458  0.554299   
3   0.539943  0.544311  0.541399  0.532663  0.518103  0.503542  0.488983   
4   0.204684  0.204684  0.206719  0.211806  0.217910  0.224014  0.229101   
5   0.491861  0.508194  0.524528  0.540862  0.553112  0.555153  0.546986   
6   0.420476  0.414139  0.401466  0.379288  0.357110  0.331763  0.309586   
7   0.706017  0.730517  0.748333  0.763924  0.772831  0.781740  0.783968   
8   0.335069  0.341984  0.344288  0.351201  0.362725  0.376552  0.390379   
9   0.245174  0.254347  0.266579  0.278811  0.291

In [446]:
import librosa as librosa
zcrs = librosa.feature.zero_crossing_rate(data)

ModuleNotFoundError: No module named 'librosa'

In [444]:
# data.mean(axis = 1)
zero_crosses

(array([ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
         9,  9, 10, 10, 11, 11, 11, 11, 12, 12, 13, 13, 13, 13, 14, 14, 15,
        15, 16, 16, 17, 17, 18, 18], dtype=int64),
 array([    0,  9134,  9135, 12607, 12608,  4288,  4290, 11975, 11976,
         7997,  7998, 15788, 15790, 14098, 14099,  6838,  6839, 15045,
        15046,  2049,  2050,  1592,  1595,  1598,  1599,   798,   799,
         4759,  4761,  4790,  4792,  9583,  9584, 13594, 13595,   320,
          321, 13432, 13433,  5199,  5201], dtype=int64))

In [391]:
x=np.asarray(data.mean(axis = 1)).reshape(1,-1)
final_h=np.delete(x,0,axis=1)
print(final_h)

[[0.47178729 0.56096657 0.45198209 0.26534339 0.54940587 0.41147495
  0.67796234 0.40821228 0.32459226 0.53498954 0.19578697 0.56123624
  0.42847722 0.44582162 0.49338172 0.48385595 0.29863048 0.47622909]]


In [1]:
X_train=np.delete(data,0,axis=1)
np.shape(data)

NameError: name 'np' is not defined

In [392]:
honest=np.vstack([honest,final_h])

In [393]:
np.shape(honest)

(3, 18)

In [394]:
honest

array([[0.55128134, 0.45791755, 0.450304  , 0.3110389 , 0.46065342,
        0.55786222, 0.69993566, 0.41881313, 0.45322563, 0.49413909,
        0.50875908, 0.33435636, 0.44090468, 0.36217755, 0.68271929,
        0.44340358, 0.31579593, 0.1584798 ],
       [0.53567629, 0.50419045, 0.52206028, 0.39170311, 0.47252144,
        0.51768451, 0.58144834, 0.39697036, 0.57598824, 0.29204829,
        0.49106362, 0.56859128, 0.42189215, 0.325104  , 0.30952379,
        0.24184516, 0.28473977, 0.20669986],
       [0.47178729, 0.56096657, 0.45198209, 0.26534339, 0.54940587,
        0.41147495, 0.67796234, 0.40821228, 0.32459226, 0.53498954,
        0.19578697, 0.56123624, 0.42847722, 0.44582162, 0.49338172,
        0.48385595, 0.29863048, 0.47622909]])

In [395]:
# honest=np.zeros(np.shape(final_h))

In [378]:
# honest=np.delete(honest,0,axis=0)

<b>Here we make three columns [irrelevant,probe,target]</b>

In [396]:
honest=honest.transpose() 

In [397]:
honest

array([[0.55128134, 0.53567629, 0.47178729],
       [0.45791755, 0.50419045, 0.56096657],
       [0.450304  , 0.52206028, 0.45198209],
       [0.3110389 , 0.39170311, 0.26534339],
       [0.46065342, 0.47252144, 0.54940587],
       [0.55786222, 0.51768451, 0.41147495],
       [0.69993566, 0.58144834, 0.67796234],
       [0.41881313, 0.39697036, 0.40821228],
       [0.45322563, 0.57598824, 0.32459226],
       [0.49413909, 0.29204829, 0.53498954],
       [0.50875908, 0.49106362, 0.19578697],
       [0.33435636, 0.56859128, 0.56123624],
       [0.44090468, 0.42189215, 0.42847722],
       [0.36217755, 0.325104  , 0.44582162],
       [0.68271929, 0.30952379, 0.49338172],
       [0.44340358, 0.24184516, 0.48385595],
       [0.31579593, 0.28473977, 0.29863048],
       [0.1584798 , 0.20669986, 0.47622909]])

In [432]:
honest_y=np.ones((18,1))
honest_y

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [399]:
# honest=np.delete(honest,(0),axis=0)

In [413]:
data_l=open_file()
print(data_l)

Enter file Name with extension target_val_norm_l.xlsx
C:\Users\mrsub\ML\Minor-Project I\All data for 14 electrodes and 30 subjects\Normalised Excel\Eleventh\Validation\target_val_norm_l.xlsx
       0         1         2         3         4         5         6      \
0   0.000000  1.000000  2.000000  3.000000  4.000000  5.000000  6.000000   
1   0.738808  0.737947  0.737086  0.734502  0.732780  0.731918  0.732780   
2   0.384733  0.388794  0.391841  0.394887  0.398948  0.401994  0.406055   
3   0.673762  0.680042  0.681611  0.681611  0.680042  0.673762  0.667483   
4   0.500344  0.501062  0.502498  0.502498  0.502498  0.500344  0.497474   
5   0.494095  0.497247  0.499139  0.501030  0.503551  0.506073  0.508595   
6   0.291357  0.287686  0.284016  0.280344  0.280344  0.278508  0.276673   
7   0.409373  0.404047  0.401385  0.398721  0.396059  0.390733  0.382745   
8   0.636238  0.629119  0.621999  0.612507  0.598268  0.586403  0.569792   
9   0.666152  0.644563  0.620276  0.595988  0.585

In [414]:
y=np.asarray(data_l.mean(axis = 1)).reshape(1,-1)
final_l=np.delete(y,0,axis=1)
print(final_l)

[[0.5993537  0.4213922  0.63984484 0.4594381  0.60965989 0.43834142
  0.43156201 0.47002099 0.51014686 0.50168676 0.49221442 0.46172007
  0.45836355 0.5542733  0.50299371 0.55028459 0.27331241 0.52287943]]


In [415]:
# lying=np.zeros((1,18))

In [416]:
lying=np.vstack([lying,final_l])

In [417]:
lying

array([[0.58452027, 0.41965459, 0.52322412, 0.56191428, 0.42718334,
        0.52670458, 0.5124958 , 0.51731515, 0.56836398, 0.49481826,
        0.27979432, 0.51803435, 0.51339376, 0.60087476, 0.48087044,
        0.58511516, 0.32908408, 0.45322431],
       [0.55128134, 0.45791755, 0.450304  , 0.3110389 , 0.46065342,
        0.55786222, 0.69993566, 0.41881313, 0.45322563, 0.49413909,
        0.50875908, 0.54035884, 0.3195427 , 0.63339253, 0.45432112,
        0.47751451, 0.47922005, 0.50678441],
       [0.5993537 , 0.4213922 , 0.63984484, 0.4594381 , 0.60965989,
        0.43834142, 0.43156201, 0.47002099, 0.51014686, 0.50168676,
        0.49221442, 0.46172007, 0.45836355, 0.5542733 , 0.50299371,
        0.55028459, 0.27331241, 0.52287943]])

In [418]:
np.shape(lying)

(3, 18)

In [419]:
# lying=np.delete(lying,(0),axis=0)

In [420]:
# a=np.asarray(final_l.mean(axis = -1))
# print(a)
# final_l=np.append(final_l,a)

In [421]:
lying=lying.transpose()

In [422]:
lying

array([[0.58452027, 0.55128134, 0.5993537 ],
       [0.41965459, 0.45791755, 0.4213922 ],
       [0.52322412, 0.450304  , 0.63984484],
       [0.56191428, 0.3110389 , 0.4594381 ],
       [0.42718334, 0.46065342, 0.60965989],
       [0.52670458, 0.55786222, 0.43834142],
       [0.5124958 , 0.69993566, 0.43156201],
       [0.51731515, 0.41881313, 0.47002099],
       [0.56836398, 0.45322563, 0.51014686],
       [0.49481826, 0.49413909, 0.50168676],
       [0.27979432, 0.50875908, 0.49221442],
       [0.51803435, 0.54035884, 0.46172007],
       [0.51339376, 0.3195427 , 0.45836355],
       [0.60087476, 0.63339253, 0.5542733 ],
       [0.48087044, 0.45432112, 0.50299371],
       [0.58511516, 0.47751451, 0.55028459],
       [0.32908408, 0.47922005, 0.27331241],
       [0.45322431, 0.50678441, 0.52287943]])

In [433]:
lying_y=np.zeros((18,1))
lying_y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [424]:
x_train=np.vstack([honest,lying])

In [425]:
(x_train)

array([[0.55128134, 0.53567629, 0.47178729],
       [0.45791755, 0.50419045, 0.56096657],
       [0.450304  , 0.52206028, 0.45198209],
       [0.3110389 , 0.39170311, 0.26534339],
       [0.46065342, 0.47252144, 0.54940587],
       [0.55786222, 0.51768451, 0.41147495],
       [0.69993566, 0.58144834, 0.67796234],
       [0.41881313, 0.39697036, 0.40821228],
       [0.45322563, 0.57598824, 0.32459226],
       [0.49413909, 0.29204829, 0.53498954],
       [0.50875908, 0.49106362, 0.19578697],
       [0.33435636, 0.56859128, 0.56123624],
       [0.44090468, 0.42189215, 0.42847722],
       [0.36217755, 0.325104  , 0.44582162],
       [0.68271929, 0.30952379, 0.49338172],
       [0.44340358, 0.24184516, 0.48385595],
       [0.31579593, 0.28473977, 0.29863048],
       [0.1584798 , 0.20669986, 0.47622909],
       [0.58452027, 0.55128134, 0.5993537 ],
       [0.41965459, 0.45791755, 0.4213922 ],
       [0.52322412, 0.450304  , 0.63984484],
       [0.56191428, 0.3110389 , 0.4594381 ],
       [0.

In [434]:
y_train=np.vstack([honest_y,lying_y])

In [435]:
y_train

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [436]:
print(np.shape(x_train))
print(np.shape(y_train))

(36, 3)
(36, 1)


In [437]:
norm_df=pd.DataFrame(y_train)
norm_df.to_excel(r'C:\Users\mrsub\ML\Minor-Project I\All data for 14 electrodes and 30 subjects\Normalised Excel\y_val11.xlsx',index=False)